version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        ENV: development
    # restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./web:/var/www/html/
    working_dir: /var/www/html/
    ports:
      - ${WEB_PORT}:80
  selenium:
    image: selenium/standalone-chrome:123.0
    shm_size: 2g
    ports:
      - "4444:4444"
    depends_on:
      - web

  e2e:
    image: python:3.11-slim
    working_dir: /tests
    volumes:
        - ./web/pos-system/tests:/tests
        - ./requirements.txt:/tests/requirements.txt
    depends_on:
      - web
      - selenium
    entrypoint: ["bash", "-lc", "pip install --no-cache-dir -r requirements.txt && pytest -q e2e"]
    extra_hosts:
    - "host.docker.internal:host-gateway"




  mysql:
    image: mysql:8.0.30
    # restart: always
    ports:
      - ${MYSQL_PORT}:3306
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    env_file:
      - ./docker/config/dev.env
    environment:
      - BIND-ADDRESS=0.0.0.0
      - TZ=Asia/Tokyo
    volumes:
      - ./data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./schema:/var/tmp
    working_dir: /var/tmp

  mail:
    image: axllent/mailpit:latest
    ports:
      - ${MAIL_SMTP_PORT}:1025
      - ${MAIL_HTTP_PORT}:8025
